<?php
/*
              -------Creado por-------
             \(x.x )/ Anarchy \( x.x)/
              ------------------------
 */

//    Quédate con quien te quiera por tu back-end, no por tu front-end  \\
include_once realpath('../../innerController/ProductosController.php');

$idPRODUCTOS = $_POST['idPRODUCTOS'];
$NOMBRE_PRODUCTO = $_POST['NOMBRE_PRODUCTO'];
$UNIDAD_PRODUCTO = $_POST['UNIDAD_PRODUCTO'];
$COSTO_PRODUCTO = $_POST['COSTO_PRODUCTO'];
$PRECIOVENTA_PRODUCTO = $_POST['PRECIOVENTA_PRODUCTO'];
$VALORMINIMO_PRODUCTO = $_POST['VALORMINIMO_PRODUCTO'];
$FECHAINGRESO_PRODUCTO = $_POST['FECHAINGRESO_PRODUCTO'];
$CATEGORIA_PRODUCTO = $_POST['CATEGORIA_PRODUCTO'];
$FECHAVENCIMIENTO_PRODUCTO = $_POST['FECHAVENCIMIENTO_PRODUCTO'];
$TIENDA_idTIENDA = $_POST['TIENDA_idTIENDA'];
$CATEGORIA_idCATEGORIA = $_POST['CATEGORIA_idCATEGORIA'];
$PROVEEDORES_idPROVEEDORES = $_POST['PROVEEDORES_idPROVEEDORES'];
$PROVEEDORES_TIENDA_idTIENDA = $_POST['PROVEEDORES_TIENDA_idTIENDA'];
ProductosController::insert($idPRODUCTOS, $NOMBRE_PRODUCTO, $UNIDAD_PRODUCTO, $COSTO_PRODUCTO, $PRECIOVENTA_PRODUCTO, $VALORMINIMO_PRODUCTO, $FECHAINGRESO_PRODUCTO, $CATEGORIA_PRODUCTO, $FECHAVENCIMIENTO_PRODUCTO, $TIENDA_idTIENDA, $CATEGORIA_idCATEGORIA, $PROVEEDORES_idPROVEEDORES, $PROVEEDORES_TIENDA_idTIENDA);
echo "true";

//That´s all folks!